apiVersion: v1
kind: Service
metadata:
  name: {{ include "PolyNSI.fullname" . }}
  labels:
    {{- include "PolyNSI.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-alt
      protocol: TCP
      name: http
  selector:
    {{- include "PolyNSI.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-grpc" (include "PolyNSI.fullname" .) }}
  labels:
    {{- include "PolyNSI.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpc }}
      targetPort: 9090
      protocol: TCP
      name: grpc
  selector:
    {{- include "PolyNSI.selectorLabels" . | nindent 4 }}
