apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "PolyNSI.fullname" . }}
  labels:
    {{- include "PolyNSI.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Chart.Name }}
  selector:
    matchLabels:
      {{- include "PolyNSI.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "PolyNSI.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "PolyNSI.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
#          command:
#            - "mvn"
#          args:
#            - "spring-boot:run"
#            - "-Dspring-boot.run.arguments=--spring.config.location=/usr/local/etc/polynsi/application.properties"
          command:
            - "java"
          args:
            - "-Dspring.config.location=/usr/local/etc/polynsi/application.properties"
            - "-jar"
            - "polynsi.jar"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-alt
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /soap
              port: http-alt
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /soap
              port: http-alt
            initialDelaySeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
              subPath: {{ .Values.persistence.subPath }}
          {{- end }}
            - name: config
              mountPath: "/usr/local/etc/polynsi"
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ printf "%s-config" (include "PolyNSI.fullname" .) }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      {{- with .Values.persistence.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
{{- end }}
